### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by fontrum** [CoolProp/REFPROP-headers#11]
I am using the REFPROP headers in order to call the DLLs from another C++ project. I am using the context that is provided in the main.cpp file, in order to point to the location of "fluids" folder.

    char mypath[] = "C:\\Program Files (x86)\\REFPROP\\";
    SETPATHdll(mypath, 400);

I am getting "Access Violation Writing Location" error for SETPATHDLL call.

**Comment by ibell** [comment]
Well, is the SETPATHdll pointer a NULL pointer?  Please show your complete
code - looks like you did not set the function pointers properly.

In C/C++, that might be a manifestation of something else going wrong.

**Comment by ibell** [comment]
What was the resolution?

**Comment by fontrum** [comment]
load function was returning "true", although it was not loading REFPROP. It was due to a change I made.
