### ISSUE TITLE
Slow 32-bit DLL access

### ISSUE THREAD

**Issue by henningjp** [CoolProp/REFPROP-headers#17]
This might be a REFPROP issue, I'm not sure.  However, I have had a Mathcad wrapper written for a decade that links in a compiled REFPROP.LIB and makes the external function calls directly.  This worked great, but I've had to recompile each version of REFPROP over the years into a new LIB and link that into a new wrapper version.

Then I figured out how CoolProp was calling the REFPROP.DLL and REFPROP64.DLL directory.  This is brilliant!  So I rewrote my wrapper and, although it works, the Mathcad 15 (32-bit) wrapper is about 100X slower than the direct calls to a linked in Fortran.  Everything I've read indicates that calling the DLL shouldn't be any slower than direct calls.  Scratching my head.

Then I compiled the exact same code as a Mathcad Prime wrapper, which is 64-bit and makes calls to REFPROP64.DLL instead.  I'm back up to speeds comparable to the original direct linked code.

Any ideas why making the calls to the 32-bit REFPROP.DLL would be that much slower?  I have a Mathcad 15 verification worksheet that used to process in less than a minute and now takes hours!  The Mathcad Prime version (same source code, 64-bit compile/link) runs the equivalent worksheet in less than a minute.  Any thoughts on how I can debug this?

Thanks.

**Comment by henningjp** [comment]
Same thing happens if I call REFPROP through the CoolProp add-in for Mathcad.   Mathcad 15, calling the 32-bit version of REFPROP.DLL is 100X slower than calling the REFPROP64.DLL in Mathcad Prime.  (Identical CoolProp source code except for being compiled as a 32-bit or 64-bit add-in).  Timing examples of an Enthalpy-Temperature plot are shown below with the elapsed time measured before and after the plot.  Each plot curve makes 1,000 calls to CoolProp with the fluid "REFPROP::Water".  This is Refprop 9.1.1.11.  

I've looked through REFPROP_lib.h and it's pretty straight forward.  Is there some optimization here for 64-bit calls that I'm missing?  Of course it could still just be that REFPROP.DLL is MUCH slower than REFPROP64.DLL and it may be resolved in Refprop 10.  Just wanted to make sure it's not something we're doing wrong in REFPROP_lib.h.

Here's the Mathcad 15 (32-bit calls) timing test:
![refprop time 15](https://user-images.githubusercontent.com/17114032/40152213-51841e6c-5952-11e8-9eb8-b25e199a17db.PNG)

Here's the Mathcad Prime 4.0 (64-bit calls) timing test:
![refprop time prime](https://user-images.githubusercontent.com/17114032/40152221-588d6650-5952-11e8-8d5e-7567125445df.PNG)

Roughly 30+ seconds to generate the plot with the 32-bit DLL and 0.3 seconds with the 64-bit DLL.  Can they really be that different?

**Comment by jowr** [comment]
It cannot explain it all, but what happens if you exclude the critical isobar? Some of the solvers might perform better in 64bit due to higher accuracy data types.

**Comment by henningjp** [comment]
The slow-down is noticeable even with just the vapor saturation curve and no isobars calculated.

100x seems exemplary, especially since the direct linked code (not through the Refprop header and REFPROP.DLL) doesn’t behave this way.  The direct linked code in 32-bit should have the same issues if it was 32-bit solver efficiency; it doesn’t.

**Comment by henningjp** [comment]
Going to close this for now.  Will update it when I get and test the 32-bit DLL in REFPROP 10.

**Comment by henningjp** [comment]
Follow up on this closed issue, now that I finally have REFPROP 10 on site.

The REFPROP 10 32-bit DLL is about 100x faster, and more in-line with the speed of the 64-bit DLL, than the one in REFPROP 9.1.1.x.  Not sure why the REFPROP 9.1.1 32-bit DLL was so slow, but this is a welcome improvement.

**Comment by ibell** [comment]
Wonder if the other 32-bit one was accidentally a debug build or something?  Glad to hear its resolved!

**Comment by henningjp** [comment]
For completeness, here are the outputs from the same benchmark files used above to wrap this up.

It's the same version of Mathcad 15, but a newer version of Prime 6.0 (vs. 4.0).  The timing with Prime 6.0 and the 64-bit REFPROP 10 DLL is actually ~2X **_slower_** than with the REFPROP 9.1.1 DLL, but Mathcad 15 using the 32-bit DLL is now slightly faster than the Prime/REFPROP10 combo and of the same order of magnitude.  There was definitely something funny with that REFPROP 9.1.1 32-bit DLL.

Here's the **Mathcad 15** (32-bit REFPROP 10 calls) timing test:
![REFPROP10 Time 15](https://user-images.githubusercontent.com/17114032/110644150-d093a280-8182-11eb-9907-5577e8308f8b.PNG)

Here's the **Mathcad Prime 6.0** (64-bit REFPROP 10 calls) timing test:
![REFPROP10 Time Prime](https://user-images.githubusercontent.com/17114032/110644164-d4272980-8182-11eb-96c1-c2c1fd80666e.PNG)
