### ISSUE TITLE
101 herr: [SETUP error 101] Error in opening file for component 1: filename = R32.FLD

### ISSUE THREAD

**Issue by tonywilliams1990** [CoolProp/REFPROP-headers#20]
I'm running the main.cpp file but I get an error when trying to open the R32.FLD file

101 herr: [SETUP error 101] Error in opening file for component 1: filename = R32.FLD

I am using Linux (Ubuntu) and g++ to compile the code. I have copied the fluid and mixture files over from a Windows installation so I was wondering whether the files aren't compatible?

**Comment by ibell** [comment]
Should be fine; what is your folder setup of shared library and fluid files?  You want them to be like:

```
librefprop.so
FLUID
MIXTURES
```

in one folder.

**Comment by tonywilliams1990** [comment]
Thanks, it's sorted now.
