### ISSUE TITLE
A possible error in REFPROP_lib.h

### ISSUE THREAD

**Issue by caidiner** [CoolProp/REFPROP-headers#21]
Hello, Mr. Bell, thanks for your time.

I have read and tested the C++ program like "main.cpp" in this repository using Visual Studio Code. An error in header file "REFPROP_lib.h" is reported, which is "A variable "t" is not defined and assigned". Its location is in line 759, column 45. 

In addition, I'm studying the real time simulation of thermodynamic time-varying system based on Simulink. Thermophysical properties of working fluids are planned to be obtained by calling C-style refprop routines. I would like to ask if there is a refprop header file based on C and an example of calling refprop in C program. 

Besides, I  want to know if there is an embedded system development case that calls refprop in real-time target machine which from Speedgoat Co.

Thanks.

**Comment by ibell** [comment]
The offending commit with git blame: https://github.com/CoolProp/REFPROP-headers/commit/786a8208f722f41fcf16da90e589110b4f1b2f8e .   I think t should be dllPath.  Can you please test and file a pull request
