### ISSUE TITLE
Refprop Integration into LabWindows

### ISSUE THREAD

**Issue by nicholaschowenchan** [CoolProp/REFPROP-headers#22]
Hi there,

I was looking into integrating a REFPROP function to calculate gas density into an existing LabWindows program. I noticed there were existing solutions for LabView and was wondering if you knew of existing examples pertaining to LabWindows?

**Comment by ibell** [comment]
I hadn't heard of LabWindows.  Consider to post this to the refprop github
page, and I can redirect to appropriate person
