### ISSUE TITLE
Fully configurable paths

### ISSUE THREAD

**Issue by jowr** [CoolProp/REFPROP-headers#6]
If it is possible, I would really like a way to load different DLLs and fluid folders. Does it make sense to work on this or are there any hardcoded names inside the shared library?

**Comment by ianhbell** [comment]
Some notes:
1) You can provide full paths to the fluid names
2) You can already provide the path to the shared library: https://github.com/CoolProp/REFPROP-headers/blob/master/REFPROP_lib.h#L532 , but I can definitely see the point of also providing the full resolved name of the shared library.  You should feel free to modify the existing function (in a backwards compatible way) to also allow you to provide the library file name.

**Comment by ibell** [comment]
3. You can also call the SETPATHdll function to direct REFPROP what the
root directory is that contains the fluids and mixtures directories
