### ISSUE TITLE
Missing commits

### ISSUE THREAD

**Issue by jowr** [CoolProp/REFPROP-headers#7]
It looks like some commits are missing from the master branch. Comparing ` REFPROP_lib.h` the HEAD and the logs suggests that fcb2c241, 183a5cdf and 5bd15ef3 have somehow been removed.

Example: The changes from  fcb2c241 in line 162 in `REFPROP_lib.h` are not present in the current master branch...

**Comment by jowr** [comment]
My theory is that @ianhbell forgot to include `REFPROP_lib.h` in 1946ad90973dfd3842d686b6ccab5c7fcb4d65e2

**Comment by ianhbell** [comment]
Hmm….  That seems possible.  Those pesky merges.  Is this something that you need me to fix, or can you cherry-pick those things back in?

**Comment by jowr** [comment]
No, I think I fixed it. Could you please review #8, which should contain all the code again?

**Comment by ibell** [comment]
Looks good to me I think.
